CODE_DATA = 4
BOARD_DATA = 288 #  8x6x6
MAP_DATA = 50    #  2x5x5
TURN_DATA = 25   #  1x5x5
FLOW_DATA = 446  #  2x5x5 + 11x6x6

S = BOARD_DATA + MAP_DATA + TURN_DATA + FLOW_DATA 
S_BOARD_MAP = BOARD_DATA + MAP_DATA
S_FLOW = FLOW_DATA
S_TURN = TURN_DATA

BOARD_POS = 36
MAP_POS = 25
TOTAL_POS = BOARD_POS + MAP_POS
MAP_POS_OFFSET = 64
