BOARD_DATA = 324
MAP_DATA = 50
FLOW_DATA = 13
TURN_DATA = 2
CODE_DATA = 4

S = BOARD_DATA + MAP_DATA + FLOW_DATA + TURN_DATA

BOARD_POS = 36
MAP_POS = 25
TOTAL_POS = BOARD_POS + MAP_POS
MAP_POS_OFFSET = 64
