CODE_DATA = 4
BOARD_DATA = 288 #  8x6x6
MAP_DATA = 50    #  2x5x5
TURN_DATA = 25   #  1x5x5
FLOW_MAP_DATA = 50  #  2x5x5
FLOW_ENV_DATA = 396  # 11x6x6
FLOW_DATA = FLOW_MAP_DATA + FLOW_ENV_DATA

S = BOARD_DATA + MAP_DATA + TURN_DATA + FLOW_DATA 
E_MAP = BOARD_DATA + MAP_DATA
E_TURN = BOARD_DATA + MAP_DATA + TURN_DATA
E_FM = BOARD_DATA + MAP_DATA + TURN_DATA + FLOW_MAP_DATA

BOARD_POS = 36
MAP_POS = 25
TOTAL_POS = BOARD_POS + MAP_POS
MAP_POS_OFFSET = 64
